### ISSUE TITLE
Add a section on previewing websites via right clicking

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/fe-environment-setup#3]
Maybe it doesn't belong here, maybe it does but we need something to explain how to preview a website you are building in the Learn IDE you just right click on the file and choose preview.

cc: @pletcher

**Comment by pletcher** [comment]
Added: https://github.com/learn-co-curriculum/html-css-learn-workflow-ide/commit/ec21a3b1b49a6f700785fd8ecef98aef90542d5c
